# Optional sound packs are downloaded with herdr-sound download.
HERDR_ALERT_BLOCKED=tesla
HERDR_ALERT_DONE=1up
HERDR_VOLUME_BLOCKED=1.8
HERDR_VOLUME_DONE=1.0
HERDR_ALERT_MAX_SECONDS=3
HERDR_ALERT_FLASH=1
HERDR_ALERT_SPRITE=1
